"""cria a unique key constraint

Revision ID: 032552bab129
Revises: 
Create Date: 2025-04-15 19:37:54.930027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032552bab129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_materia', ['nome', 'serie', 'escola_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_constraint('unique_materia', type_='unique')

    # ### end Alembic commands ###
