"""empty message

Revision ID: 0dfd2ea7d79b
Revises: 032552bab129
Create Date: 2025-04-15 20:20:27.707735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfd2ea7d79b'
down_revision = '032552bab129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')

    # ### end Alembic commands ###
